### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#163]
"Traceback (most recent call last):
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/util.py", line 870, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 1464, in run
    self.wait_on_sockets()
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 1438, in wait_on_sockets
    self.process_responses(interface)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 862, in process_responses
    self.process_response(interface, request, response, callbacks)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 763, in process_response
    self.on_notify_header(interface, result)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 1505, in on_notify_header
    self._process_latest_tip(interface)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/network.py", line 1521, in _process_latest_tip
    b = blockchain.can_connect(header) # Is it the next header on a given blockchain.
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 143, in can_connect
    if b.can_connect(header):
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 586, in can_connect
    bits = self.get_bits(header)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 485, in get_bits
    anchor = self.get_asert_anchor(prior, daa_mtp, chunk)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 447, in get_asert_anchor
    prev_mtp = self.get_median_time_past(ht - 1, chunk)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 405, in get_median_time_past
    for h in range(max(0, height - 10), height + 1)
  File "/tmp/.mount_Electrgrp1y3/usr/lib/python3.6/site-packages/electroncash/blockchain.py", line 405, in <listcomp>
    for h in range(max(0, height - 10), height + 1)
TypeError: 'NoneType' object is not subscriptable
 
Additional information
    • Electron Cash version: 3.6.6 
    • Python version: 3.6.9 (default, Jun 28 2018, 19:01:02) [GCC 5.4.0 20160609] 
    • Operating system: Linux-5.4.0-58-generic-x86_64-with-debian-buster-sid 
    • Wallet type: slp_standard"

**Comment by jcramer** [comment]
Investigating, this looks similar to https://github.com/Electron-Cash/Electron-Cash/issues/2071.

**Comment by jcramer** [comment]
Fixed with cherry-pick of: 34d68657d6d3091103212f84b465c638fa65dea7
