### ISSUE TITLE
Unable to send Exception slp pre-flight check failed connection error certificate has expired

### ISSUE THREAD

**Issue by damascene** [simpleledger/Electron-Cash-SLP#230]
I'm using EC SLP from command line and I'm getting this error when I try to send any amount. It works sometimes and it fails others with the same exact command for the same error. Also similar error on testnet for the testnet server.

The owner of the domain said he had updated the certificate recently after it expired.

```bash
$ ./electron-cash -w minting_test2 payto bitcoincash:qq0xhchpmgs8ytfjyc02w4pjvl65mlntyydxpytfp5 0.00001
Traceback (most recent call last):
  File "./electron-cash", line 594, in <module>
    main()
  File "./electron-cash", line 586, in main
    result = run_cmdline(config, config_options, cmdname)
  File "./electron-cash", line 426, in run_cmdline
    result = server.run_cmdline(config_options)
  File "/home/user/slp_buy_bot/venv/lib/python3.8/site-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/home/user/slp_buy_bot/venv/lib/python3.8/site-packages/jsonrpclib/jsonrpc.py", line 696, in _request
    check_for_errors(response)
  File "/home/user/slp_buy_bot/venv/lib/python3.8/site-packages/jsonrpclib/jsonrpc.py", line 1453, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/home/user/slp_buy_bot/src/Electron-Cash-SLP/electroncash/slp_checker.py", line 257, in check_tx_slp | Exception: slp pre-flight check failed: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2021-11-25T01:53:16-05:00 is after 2021-11-18T12:00:00Z"\n\n(node: https://bchd-mainnet.electroncash.de)\n')
```

**Comment by damascene** [comment]
Other  user reported the issue on the Desktop version. 
![image](https://user-images.githubusercontent.com/411046/143425688-a2c911aa-c8bd-4e3b-9582-81cb783ab7ee.png)
