### ISSUE TITLE
Cannot send tokens

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#36]
When sending and SLP token from latest githead: 

Traceback (most recent call last):
  File "/home/user/bin/slp/electrum/gui/qt/main_window.py", line 1866, in do_send
    r = self.read_send_tab(preview=preview)
  File "/home/user/bin/slp/electrum/gui/qt/main_window.py", line 1753, in read_send_tab
    if NetworkConstants.SLPADDR_PREFIX not in self.payto_e.address_string_for_slp_check:
NameError: name 'NetworkConstants' is not defined

**Comment by imaginaryusername** [comment]
https://github.com/simpleledger/Electron-Cash-SLP/commit/abf7e82e19a72934619904a2b0af0f81037478c0 seems to fix it, thanks!
