### ISSUE TITLE
add token context menu fails

### ISSUE THREAD

**Issue by markblundeberg** [simpleledger/Electron-Cash-SLP#62]
In today's master, receiving unknown token then right click -> add token in the SLP History tab
```
Traceback (most recent call last):
  File "/home/mark/git/slp/gui/qt/slp_history_list.py", line 227, in <lambda>
    menu.addAction(_("Add this token"), lambda: SlpAddTokenDialog(self.parent, token_id_hex = token_id))
  File "/home/mark/git/slp/gui/qt/slp_add_token_dialog.py", line 68, in __init__
    self.token_id_e.addCopyButton(self.app)
TypeError: addCopyButton() takes 1 positional argument but 2 were given
```

**Comment by jcramer** [comment]
Thankfully I'm having a hard time reproducing.  I am thinking that this is a similar issue to #53.  Will fix it today.

**Comment by jcramer** [comment]
thank you for catching this, looks like caused by changes to addCopyButton() in recent commit 6e2fd80b2
